name: Sync with Guide
description: Synchronizes the content of the Hugo site with Guide using the External Content API.
inputs:
  content-dir:
    description: Path to directory where HTML files are located.
    required: true
    default: '.'
  working-dir:
    description: Working directory.
    required: true
    default: "."
  target-base-url:
    description: |
      Base URL that should prefix all paths found in `content-dir`. If `working-dir` is provided, the paths will be relative to that dir.
    required: true
  source-id:
    description: The ID of the External Content Source in Zendesk Guide.
    required: true
  type-id:
    description: The ID of the External Content Type in Zendesk Guide.
    required: true
  auth:
    description: Authentication Credentials, e.g. `my@email.com:password`.
    required: true
  zendesk-subdomain:
    description: The subdomain of your Zendesk account.
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    CONTENT_DIR: ${{ inputs.content-dir }}
    WORKING_DIR: ${{ inputs.working-dir }}
    EXTERNAL_CONTENT_SOURCE_ID: ${{ inputs.source-id }}
    EXTERNAL_CONTENT_TYPE_ID: ${{ inputs.type-id }}
    ZENDESK_AUTH: ${{ inputs.auth }}
    ZENDESK_BASE_URL: "https://${{ inputs.zendesk-subdomain }}.zendesk.com"
    TARGET_BASE_URL: ${{ inputs.target-base-url }}
