name: Index in Guide Search

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: ./
        name: Sync with the Guide Search Index
        with:
          client-id: ${{ secrets.ZENDESK_CLIENT_ID }}
          client-secret: ${{ secrets.ZENDESK_CLIENT_SECRET }}
          zendesk-subdomain: z3nab-e418d8-302d0911231564b6db7a9964c378735668b64e
          source-id: "01KZ8VRGJTNJ7GT2BRYHTXZE4K"
          type-id: "01KZ8VRH998FHPTAMTHS6SA3BF"
          content-dir: "test"
          target-base-url: "https://wikipedia.org"
