name: Index in Guide Search

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: ./
        name: Sync with the Guide Search Index
        with:
          auth: ${{ secrets.ZENDESK_AUTH }}
          zendesk-subdomain: z3n-dasch
          source-id: "01EV9B6T8YH7672NFGPBBYAXGT"
          type-id: "01EV9B8DJ0668KRW653EFYA9NW"
          content-dir: "test"
          target-base-url: "https://wikipedia.org"
